### ISSUE TITLE
Plans for a logback appender?

### ISSUE THREAD

**Issue by gkopff** [MindscapeHQ/raygun4java#16]
Is there any plans for providing a logback appender to capture exceptions from log messages and send them?

(In previous projects we've used Airbrake, and we also like to emit WARN and ERROR messages (even without an exception), because they're just as critical an an uncaught exception).

**Comment by fundead** [comment]
Thanks for open sourcing that, I'm sure others in the community will greatly appreciate that. Will close this issue for now.
