### ISSUE TITLE
Headless server RaygunEnvironmentMessage does not gather data

### ISSUE THREAD

**Issue by sstarcher** [MindscapeHQ/raygun4java#18]
on a headless server
```
windowBoundsWidth = GraphicsEnvironment
					.getLocalGraphicsEnvironment().getMaximumWindowBounds().width;
```
causes an issue due to X11 not existing

**Comment by q42jaap** [comment]
This is spamming our logs :( Which data is recorded should be a setting so we can turn them off.

**Comment by sstarcher** [comment]
@q42jaap you can configure the logger to turn off the warn from that class, but without the pull request I linked it only gets part of the data.

**Comment by q42jaap** [comment]
how would the "from that class" part work in logback xml config?

**Comment by sstarcher** [comment]
@q42jaap I believe your correct you could only filter out all Raygun4Java loggers.

**Comment by CmdrKeen** [comment]
Hi Folks, 

We'll have a look into this next week, sorry about the delay.
