### ISSUE TITLE
raygun4java-play2 1.6.0 can't be resolved

### ISSUE THREAD

**Issue by eamelink** [MindscapeHQ/raygun4java#23]
There is something weird going on with the raygun4java-play2 1.6.0 artifact; SBT fails to resolve it. 

In an empty SBT 0.13.7 project, with only the following contents in `build.sbt`

    libraryDependencies += "com.mindscapehq" % "raygun4java-play2" % "1.6.0"

It fails to resolve it with this error message:

    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	::              FAILED DOWNLOADS            ::
    [warn] 	:: ^ see resolution messages for details  ^ ::
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	:: com.mindscapehq#raygun4java-play2;1.6.0!raygun4java-play2.play2
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::

Note that it tries to resolve a file `raygun4java-play2.play2` instead of `raygun4java-play2.jar`. I have no idea why this happens.

**Comment by kristijanbambir** [comment]
I can confirm this.

**Comment by fundead** [comment]
Thanks for reporting this one, we'll be looking into it shortly and will let you know the results.

**Comment by fundead** [comment]
Just a note, the v1.6.0 JAR looks to be working corectly at  http://search.maven.org/#artifactdetails%7Ccom.mindscapehq%7Craygun4java-play2%7C1.6.0%7Cplay2, will have a fix for sbt resolving it incorrectly in the very near future.

**Comment by eamelink** [comment]
Any progress on this? The culprit seems to be an incorrect `packaging` field in the POM:

    <packaging>play2</packaging>

That should be 

    <packaging>jar</packaging>

**Comment by fundead** [comment]
Thanks for that, this has now been released as v1.6.1 and should be available from Maven Central within 24 hours.
