### ISSUE TITLE
How to integrate with Spring application?

### ISSUE THREAD

**Issue by Paxa** [MindscapeHQ/raygun4java#30]

**Comment by tobiasmh** [comment]
Are you able to elaborate a bit more on your question? Are you wanting to implement it with Spring MVC or another messaging pattern using spring?

If it is for Spring MVC a great starting point is using the Spring MVC interceptors: http://www.mkyong.com/spring-mvc/spring-mvc-handler-interceptors-example/ You can catch all the exceptions with the interceptor and then pass them on to Raygun for its further processing.

**Comment by Paxa** [comment]
Yes, Spring MVC. Thank you
