### ISSUE TITLE
Error without Throwable crashes

### ISSUE THREAD

**Issue by jbedard** [MindscapeHQ/raygun4java#33]
Is this valid?

I want to send all log messages of level ERROR to raygun but not all have exceptions. Currently `RaygunClient.Send` requires a `Throwable` and if it is null it crashes...

**Comment by fundead** [comment]
My apologies for the delay in the response to this ticket. Just an update on this one, Raygun Crash Reporting currently requires an Exception-type object (e.g inheriting from Throwable in Java) as the backend requires a stack trace to perform the auto-grouping and to get the best value out of the interface and product (which is highly tuned for surfacing and exploring exceptions). A system to handle generic logging is currently out of scope for Crash Reporting so log messages aren't really supported as a first-class citizen by Raygun.

We may look into a system which has support for this in the future, but we currently don't have any plans around this today.
