### ISSUE TITLE
InetAddress.getLocalHost().getHostName() throws UnkownHostException

### ISSUE THREAD

**Issue by anssip** [MindscapeHQ/raygun4java#36]
```
java.net.UnknownHostException: ip-172-29-0-123: ip-172-29-0-123
        at java.net.InetAddress.getLocalHost(InetAddress.java:1461)
        at com.mindscapehq.raygun4java.core.RaygunClient.BuildMessage(RaygunClient.java:76)
        at com.mindscapehq.raygun4java.core.RaygunClient.Send(RaygunClient.java:61)
...
```

Because of this it does not send the message to Raygun. This can be worked around by [adding a line to /etc/hosts](http://stackoverflow.com/questions/1881546/inetaddress-getlocalhost-throws-unknownhostexception). Would be great if this worked without this workaround -- our EC2 instances by default are 'incompatible" with the raygun Java client because of this issue.

**Comment by fundead** [comment]
Thanks for reporting this one, I can add a guard to the affected code path to ensure the workaround isn't needed. I'll look at getting this in for you during out next sprint.
