### ISSUE TITLE
Returning null from OnBeforeSend handler sends "null" message

### ISSUE THREAD

**Issue by johnsdouglass** [MindscapeHQ/raygun4java#37]
I'm trying out the new OnBeforeSend handler. I noticed that returning null from the handler, which according to the documentation should cancel the send, actually sends the text "null". You can see it by tracing step-by-step in a debugger.

The RaygunClient Post command should just return after the "_onBeforeSend.OnBeforeSend(raygunMessage);" call, if raygunMessage == null.

**Comment by fundead** [comment]
Right you are, thanks for spotting this one. I'll aim to get a point release out to fix this one for you today or tomorrow.
