### ISSUE TITLE
is Java APM support officially supported?

### ISSUE THREAD

**Issue by mjobin-mdsol** [MindscapeHQ/raygun4java#73]
Not finding it in this list .. 
![image](https://user-images.githubusercontent.com/1864520/98208699-121c0300-1f81-11eb-88f1-19d54d8d6d62.png)

but I found this project, so I am wondering, if this is something we can test out

**Comment by Deacon-McIntyre** [comment]
Hi @mjobin-mdsol , thanks for your interest! Unfortunately Raygun's APM product does not yet support Java, but we've recorded your request for this.

Raygun4java is for our [Crash Reporting](https://raygun.com/documentation/language-guides/java/crash-reporting/installation/) product, not APM.
